# GENERATED by p4_codegen/generate.py from _async/ - do not edit.
"""caldav's mistake, planted in async-first source, in three shapes.

``generate.py`` turns it into ``../_sync/buggy.py``, where each slip is a
*correct* sync call.  So the sync test suite passes and only async users lose
the write - the asymmetry that makes p1 dangerous, reproduced in p4.

``test_type_checker_flags_the_codegen_slip`` pins what a type checker makes of
each shape, the misses included, so that the limits in section 5 of
SYNC_ASYNC_ARCHITECTURE.md are asserted rather than claimed.
"""

from __future__ import annotations

from p4_codegen._sync.tasks import SyncTask


class SyncBuggyTask(SyncTask):
    def uncomplete(self) -> SyncTask:
        self.status = "NEEDS-ACTION"
        self.save()  # SLIP bare: caught by default mypy and pyright
        return self

    def _touch(self):
        self.save()  # SLIP untyped: default mypy skips unannotated bodies

    def save_all(self, tasks: list[SyncTask]) -> None:
        [t.save() for t in tasks]  # SLIP comprehension: neither checker errors
