# GENERATED by p4_codegen/generate.py from _async/ - do not edit.
"""Prototype 4: async-first, sync generated by ``unasync`` (httpcore pattern).

This file is the only hand-written implementation.  ``generate.py`` runs
``unasync`` over it and writes ``../_sync/tasks.py``, which is committed, so
installing the library needs no build step; ``test_conformance.py`` fails if
the committed copy is stale.

unasync works on tokens, not on meaning: it drops ``async`` and ``await`` and
renames ``AsyncFoo`` to ``SyncFoo``.  That is the whole contract a contributor
has to keep in mind, and the reason everything here is spelled so that the
token rewrite is also a correct sync program.

Composition is ordinary ``await self.save()``.  Forgetting the ``await`` is
caldav's bug again, and here the generated sync copy is *correct* - the
mistake exists in async mode only, as in p1.  What catches it is measured in
``p4_codegen/_async/buggy.py`` and section 5 of SYNC_ASYNC_ARCHITECTURE.md.
"""

from __future__ import annotations

from typing import Any

from common import SyncTransport, Request, Task


class SyncCollection:
    def __init__(self, transport: SyncTransport) -> None:
        self._transport = transport

    def _new_task(self, d: dict[str, Any]) -> SyncTask:
        task = SyncTask.from_dict(d)
        task._collection = self
        return task

    def get_task(self, uid: str) -> SyncTask:
        resp = self._transport.request(Request("GET", f"/tasks/{uid}"))
        if resp.status == 404:
            raise KeyError("no such task")
        return self._new_task(resp.body)

    def search(self) -> list[SyncTask]:
        out: list[SyncTask] = []
        cursor: int | None = 0
        while cursor is not None:
            resp = self._transport.request(Request("GET", f"/search?cursor={cursor}"))
            out.extend(self._new_task(d) for d in resp.body["items"])
            cursor = resp.body["next"]
        return out


class SyncTask(Task):
    _collection: SyncCollection

    def save(self) -> SyncTask:
        self._collection._transport.request(
            Request("PUT", f"/tasks/{self.uid}", self.to_json())
        )
        return self

    def complete(self) -> SyncTask:
        fresh = self._collection.get_task(self.uid)
        self.summary = fresh.summary
        self.status = "COMPLETED"
        self.save()
        return self

    def uncomplete(self) -> SyncTask:
        self.status = "NEEDS-ACTION"
        self.save()
        return self
