"""Regenerate ``_sync/`` from ``_async/`` with unasync.

    cd prototypes/sync_async && uv run --with unasync python p4_codegen/generate.py

The output is committed.  ``test_generated_sync_code_is_fresh`` regenerates
into a temporary directory and fails on any difference - in content *or* in
the set of files - which is how httpcore keeps the same arrangement honest
without a build step at install time.

Every non-empty source file starts with a one-line comment, which the
generator replaces with the do-not-edit marker.  That keeps line numbers equal
in both copies, so a traceback through ``_sync/`` names the same line as the
source it came from.
"""

from __future__ import annotations

import shutil
import sys
import tempfile
from pathlib import Path

import unasync

HERE = Path(__file__).parent
MARKER = "# GENERATED by p4_codegen/generate.py from _async/ - do not edit.\n"
RULE = unasync.Rule("/_async/", "/_sync/", additional_replacements={"_async": "_sync"})


def generate(out_root: Path = HERE, src_root: Path = HERE) -> set[Path]:
    """Write ``out_root/_sync`` from ``src_root/_async/``, recursively; delete orphans.

    Returns the generated paths, relative to ``_sync/``.  ``src_root`` lets
    p5_adapter reuse this generator for its own ``_async/``.
    """
    dst = out_root / "_sync"
    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp) / "_async"
        shutil.copytree(src_root / "_async", work, ignore=shutil.ignore_patterns("__pycache__"))
        unasync.unasync_files([str(p) for p in sorted(work.rglob("*.py"))], [RULE])
        produced = Path(tmp) / "_sync"
        expected = {p.relative_to(produced) for p in produced.rglob("*.py")}
        for rel in sorted(expected):
            lines = (produced / rel).read_text().splitlines(keepends=True)
            if lines:
                if not lines[0].startswith("#"):
                    raise ValueError(f"_async/{rel} must start with a one-line comment")
                lines[0] = MARKER
            (dst / rel).parent.mkdir(parents=True, exist_ok=True)
            (dst / rel).write_text("".join(lines))
    for old in list(dst.rglob("*.py")) if dst.exists() else []:
        if old.relative_to(dst) not in expected:
            old.unlink()
    return expected


if __name__ == "__main__":
    for rel in sorted(generate()):
        print(f"_sync/{rel}")
    sys.exit(0)
