"""Regenerate ``_sync/`` from ``_async/`` with unasync.

    uv run --with unasync python p4_codegen/generate.py

The output is committed.  ``test_generated_sync_code_is_fresh`` regenerates
into a temporary directory and fails on any difference, which is how httpcore
keeps the same arrangement honest without a build step at install time.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

import unasync

HERE = Path(__file__).parent
HEADER = "# GENERATED by p4_codegen/generate.py from _async/ - do not edit.\n"


def generate(out_root: Path = HERE) -> list[Path]:
    """Write the sync copies of every ``_async/*.py`` under ``out_root/_sync``."""
    src = sorted((HERE / "_async").glob("*.py"))
    with_tmp = out_root != HERE
    if with_tmp:
        shutil.copytree(HERE / "_async", out_root / "_async", dirs_exist_ok=True)
        src = sorted((out_root / "_async").glob("*.py"))
    rule = unasync.Rule("/_async/", "/_sync/", additional_replacements={"_async": "_sync"})
    unasync.unasync_files([str(p) for p in src], [rule])
    out = sorted((out_root / "_sync").glob("*.py"))
    for p in out:
        if p.name != "__init__.py":
            p.write_text(HEADER + p.read_text())
    return out


if __name__ == "__main__":
    for p in generate():
        print(p.relative_to(HERE))
    sys.exit(0)
