# GENERATED by p4_codegen/generate.py from _async/ - do not edit.
"""p5's I/O, written once in async form; ``_sync/ops.py`` is generated.

The facade is what ``item.aio`` returns (``item.sync`` in the generated copy).
It holds the adapter by composition rather than being a subclass of the data,
which is the only structural difference from p4's ``AsyncTask``.
"""

from __future__ import annotations

from typing import Any

from common import SyncTransport, Request, Task
from p5_adapter.adapter import SyncMode, GatherMode, Immediate, ModeError, TaskAdapter


class SyncCollection:
    def __init__(self, transport: SyncTransport) -> None:
        self._transport = transport
        self.facade_class = SyncFacade
        self.strategy = Immediate(self, SyncMode)

    def _wrap(self, d: dict[str, Any]) -> TaskAdapter[SyncMode]:
        return TaskAdapter(Task.from_dict(d), self.strategy)

    def get_task(self, uid: str) -> TaskAdapter[SyncMode]:
        resp = self._transport.request(Request("GET", f"/tasks/{uid}"))
        if resp.status == 404:
            raise KeyError("no such task")
        return self._wrap(resp.body)

    def search(self) -> list[TaskAdapter[SyncMode]]:
        out: list[TaskAdapter[SyncMode]] = []
        cursor: int | None = 0
        while cursor is not None:
            resp = self._transport.request(Request("GET", f"/search?cursor={cursor}"))
            out.extend(self._wrap(d) for d in resp.body["items"])
            cursor = resp.body["next"]
        return out


class SyncFacade:
    def __init__(self, item: TaskAdapter[Any], collection: SyncCollection) -> None:
        self._item = item
        self._collection = collection

    def save(self) -> TaskAdapter[Any]:
        item = self._item
        self._collection._transport.request(
            Request("PUT", f"/tasks/{item.uid}", item._data.to_json())
        )
        item.dirty = False
        return item

    def complete(self) -> TaskAdapter[Any]:
        fresh = self._collection.get_task(self._item.uid)
        self._item._data.summary = fresh.summary
        self._item._data.status = "COMPLETED"
        self.save()
        return self._item

    def uncomplete(self) -> TaskAdapter[Any]:
        self._item._data.status = "NEEDS-ACTION"
        self.save()
        return self._item


class SyncGather:
    """Modes 2 of the review: record what needs writing, write it on flush().

    Queueing is mode-free; only ``flush`` does I/O, so it is the only method
    that differs between the async source and the generated sync copy.
    Repeated modifications of one item coalesce into one ``save``.
    """

    def __init__(self, collection: SyncCollection) -> None:
        self.collection = collection
        self.mode = GatherMode
        self.queue: list[tuple[TaskAdapter[Any], str]] = []

    def track(self, item: TaskAdapter[Any]) -> TaskAdapter[GatherMode]:
        """Rebind an item to this strategy; returns the same object, retyped."""
        item._strategy = self
        return item  # type: ignore[return-value]

    def require(self, mode: type, via: str) -> None:
        raise ModeError(f"{via} on a gathered item; call flush() instead")

    def facade(self, item: TaskAdapter[Any]) -> SyncFacade:
        return self.collection.facade_class(item, self.collection)

    def notify(self, item: TaskAdapter[Any]) -> None:
        self.submit(item, "save")

    def submit(self, item: TaskAdapter[Any], op: str) -> None:
        if (item, op) not in self.queue:
            self.queue.append((item, op))

    def flush(self) -> None:
        while self.queue:
            item, op = self.queue.pop(0)
            getattr(self.facade(item), op)()
