"""Prototype 5: one mode-free adapter per item, reached through per-mode facades.

The shape proposed in the PR 5 review
(https://github.com/pycalendar/calendaring/pull/5#discussion_r4237462075):
instead of a bound subclass per mode (``AsyncTask(Task)``, p4 and A1), every
item is one ``TaskAdapter`` that wraps the data and holds a *strategy*.  The
strategy decides what an I/O call means:

    item.summary = "x"           # mode-free; marks the item dirty ("borrowing")
    item.sync.save()             # sync facade
    await item.aio.save()        # async facade (``.async`` is a SyntaxError)
    item.save()                  # bare call: the strategy decides -
                                 #   Immediate(sync)  runs it now
                                 #   Immediate(async) raises ModeError
                                 #   Gather           queues it for flush()

The I/O itself is written once, in ``_async/ops.py``, and the sync copy is
generated by p4's unasync generator - so p5 is an API shape *on top of* p4,
not an alternative to it.  What is hand-written here is mode-free: the adapter,
the mode markers, and the strategies whose behaviour does not depend on I/O.

The mode is a type parameter as well as a runtime value.  ``.sync``, ``.aio``
and the bare methods carry a self-type, so a type checker rejects
``item.sync`` on an item read from an async collection, the same way it
rejects a missing ``await`` in p4 (``typing_probe/probe_p5_adapter.py``).
"""

from __future__ import annotations

from collections.abc import Iterator
from contextlib import contextmanager
from typing import TYPE_CHECKING, Any, Generic, TypeVar

from common import Task

if TYPE_CHECKING:
    from p5_adapter._async.ops import AsyncFacade
    from p5_adapter._sync.ops import SyncFacade


class BlockingMode:
    """Modes in which a bare, non-awaited I/O call is allowed."""


class SyncMode(BlockingMode):
    pass


class GatherMode(BlockingMode):
    """A bare call only queues; ``flush()`` does the I/O, in either mode."""


class AsyncMode:
    pass


M = TypeVar("M", covariant=True)


class ModeError(TypeError):
    """An I/O call was made through the wrong mode for this item's strategy."""


class TaskAdapter(Generic[M]):
    """The item.  Data access is mode-free; I/O goes through the strategy."""

    def __init__(self, data: Task, strategy: Any) -> None:
        self._data = data
        self._strategy = strategy
        self.dirty = False

    def __repr__(self) -> str:
        return f"TaskAdapter({self._data!r}, {type(self._strategy).__name__})"

    # -- data: mode-free --------------------------------------------------

    @property
    def uid(self) -> str:
        return self._data.uid

    @property
    def summary(self) -> str:
        return self._data.summary

    @summary.setter
    def summary(self, value: str) -> None:
        with self._borrowed() as data:
            data.summary = value

    @property
    def status(self) -> str:
        return self._data.status

    @status.setter
    def status(self, value: str) -> None:
        with self._borrowed() as data:
            data.status = value

    @contextmanager
    def _borrowed(self) -> Iterator[Task]:
        """Lend out the data for writing; mark dirty and notify on the way back.

        Nested borrows notify once, when the outermost one returns.  A borrow
        that raises still marks the item dirty (the data may have changed)
        but notifies nobody, so Autosync never writes a half-done edit.
        """
        outer = not getattr(self, "_borrow_depth", 0)
        self._borrow_depth = getattr(self, "_borrow_depth", 0) + 1
        try:
            yield self._data
        finally:
            self._borrow_depth -= 1
            self.dirty = True
        if outer:
            self._strategy.notify(self)

    def as_data(self) -> Task:
        """A plain copy, for pickling or handing to the other mode."""
        return Task(self._data.uid, self._data.summary, self._data.status)

    # -- I/O: per mode ----------------------------------------------------

    @property
    def sync(self: TaskAdapter[SyncMode]) -> SyncFacade:
        self._strategy.require(SyncMode, ".sync")
        return self._strategy.facade(self)

    @property
    def aio(self: TaskAdapter[AsyncMode]) -> AsyncFacade:
        self._strategy.require(AsyncMode, ".aio")
        return self._strategy.facade(self)

    def save(self: TaskAdapter[BlockingMode]) -> None:
        self._strategy.submit(self, "save")

    def complete(self: TaskAdapter[BlockingMode]) -> None:
        self._strategy.submit(self, "complete")

    def uncomplete(self: TaskAdapter[BlockingMode]) -> None:
        self._strategy.submit(self, "uncomplete")


class Immediate:
    """The default strategy: I/O happens when the caller asks for it.

    One hand-written class serves both modes; the collection supplies its
    generated facade class.  In async mode a bare call raises *before* any
    coroutine exists, so nothing is ever silently dropped.
    """

    def __init__(self, collection: Any, mode: type) -> None:
        self.collection = collection
        self.mode = mode

    def require(self, mode: type, via: str) -> None:
        if self.mode is not mode:
            raise ModeError(f"{via} on an item whose collection is {self.mode.__name__}")

    def facade(self, item: TaskAdapter[Any]) -> Any:
        return self.collection.facade_class(item, self.collection)

    def notify(self, item: TaskAdapter[Any]) -> None:
        pass

    def submit(self, item: TaskAdapter[Any], op: str) -> None:
        if self.mode is AsyncMode:
            raise ModeError(f"item.{op}() in async mode; use 'await item.aio.{op}()'")
        getattr(self.facade(item), op)()


class Autosync(Immediate):
    """Mode 1 of the review: every modification is written at once.

    Sync only.  A setter cannot await, so the async equivalent is a background
    task (mode 3), which needs ``asyncio.create_task`` - something unasync
    cannot translate, so it would be hand-written per mode.  Not prototyped.
    """

    def __init__(self, collection: Any) -> None:
        super().__init__(collection, SyncMode)

    def notify(self, item: TaskAdapter[Any]) -> None:
        self.facade(item).save()
