# Hand-written source; generate.py derives ../_sync/ from this file.
"""Prototype 4: async-first, sync generated by ``unasync`` (httpcore pattern).

This file is the only hand-written implementation.  ``generate.py`` runs
``unasync`` over it and writes ``../_sync/tasks.py``, which is committed, so
installing the library needs no build step; ``test_conformance.py`` fails if
the committed copy is stale.

unasync works on tokens, not on meaning: it drops ``async`` and ``await`` and
renames ``AsyncFoo`` to ``SyncFoo``.  That is the whole contract a contributor
has to keep in mind, and the reason everything here is spelled so that the
token rewrite is also a correct sync program.

Composition is ordinary ``await self.save()``.  Forgetting the ``await`` is
caldav's bug again, and here the generated sync copy is *correct* - the
mistake exists in async mode only, as in p1.  What catches it is measured in
``p4_codegen/_async/buggy.py`` and section 5 of SYNC_ASYNC_ARCHITECTURE.md.
"""

from __future__ import annotations

from typing import Any

from common import AsyncTransport, Request, Task


class AsyncCollection:
    def __init__(self, transport: AsyncTransport) -> None:
        self._transport = transport

    def _new_task(self, d: dict[str, Any]) -> AsyncTask:
        task = AsyncTask.from_dict(d)
        task._collection = self
        return task

    async def get_task(self, uid: str) -> AsyncTask:
        resp = await self._transport.request(Request("GET", f"/tasks/{uid}"))
        if resp.status == 404:
            raise KeyError("no such task")
        return self._new_task(resp.body)

    async def search(self) -> list[AsyncTask]:
        out: list[AsyncTask] = []
        cursor: int | None = 0
        while cursor is not None:
            resp = await self._transport.request(Request("GET", f"/search?cursor={cursor}"))
            out.extend(self._new_task(d) for d in resp.body["items"])
            cursor = resp.body["next"]
        return out


class AsyncTask(Task):
    _collection: AsyncCollection

    async def save(self) -> AsyncTask:
        await self._collection._transport.request(
            Request("PUT", f"/tasks/{self.uid}", self.to_json())
        )
        return self

    async def complete(self) -> AsyncTask:
        fresh = await self._collection.get_task(self.uid)
        self.summary = fresh.summary
        self.status = "COMPLETED"
        await self.save()
        return self

    async def uncomplete(self) -> AsyncTask:
        self.status = "NEEDS-ACTION"
        await self.save()
        return self
